function [W,RHS] = BallAndBeamODEMatrices(in1,To,in3)
%BallAndBeamODEMatrices
%    [W,RHS] = BallAndBeamODEMatrices(IN1,To,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    24-Feb-2023 16:44:24

J = in3(1,:);
M = in3(2,:);
R = in3(3,:);
dtheta = in1(4,:);
g = in3(4,:);
theta = in1(2,:);
x = in1(1,:);
t2 = sin(theta);
t3 = M.*2.0;
t4 = R.^2;
t5 = t3-5.0;
t6 = (R.*t5)./5.0;
W = reshape([M.*(2.0./5.0)+1.0,t6,t6,J+t4+M.*t4.*(2.0./5.0)+x.^2],[2,2]);
if nargout > 1
    RHS = [-dtheta.^2.*x-M.*g.*t2;To+M.*g.*(R.*t2-x.*cos(theta))];
end
