function p = BallPosition(in1,in2)
%BallPosition
%    P = BallPosition(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    24-Feb-2023 16:44:23

R = in2(3,:);
theta = in1(2,:);
x = in1(1,:);
t2 = cos(theta);
t3 = sin(theta);
p = [-R.*t3+t2.*x;R.*t2+t3.*x];
