function [W,RHS] = PendulumODEMatrices(in1,F,in3)
%PendulumODEMatrices
%    [W,RHS] = PendulumODEMatrices(IN1,F,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    24-Feb-2023 15:50:51

L = in3(3,:);
M = in3(2,:);
dtheta1 = in1(5,:);
dtheta2 = in1(6,:);
dx = in1(4,:);
g = in3(4,:);
m = in3(1,:);
theta1 = in1(2,:);
theta2 = in1(3,:);
t2 = cos(theta1);
t3 = cos(theta2);
t4 = sin(theta1);
t5 = sin(theta2);
t6 = L.^2;
t7 = -theta2;
t8 = L.*m.*t3;
t9 = t7+theta1;
t10 = L.*m.*t2.*2.0;
t11 = cos(t9);
t12 = sin(t9);
t13 = m.*t6.*t11;
W = reshape([M+m.*2.0,t10,t8,t10,m.*t6.*2.0,t13,t8,t13,m.*t6],[3,3]);
if nargout > 1
    RHS = [F;L.*dtheta1.*m.*(dx.*t4.*2.0+L.*dtheta2.*t12)-L.*M.*g.*t4.*2.0;L.*dtheta2.*m.*(dx.*t5-L.*dtheta1.*t12)-L.*M.*g.*t5];
end
